<?php

namespace Flower\FinancesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository
{
    public function getQuickStats($type)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select("SUM(je.debit) as debit, SUM(je.credit) as credit");
        $qb->join("a.journalEntries", "je");
        $qb->where("a.type = :type")->setParameter(":type", $type);

        return $qb->getQuery()->getResult();
    }
}
