<?php

namespace Flower\FinancesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerInvoiceItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerInvoiceItemRepository extends EntityRepository
{
}
