<?php

namespace Flower\FinancesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
    public function getQuickStats($type, \DateTime $date = null)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select("SUM(p.amount) as amount");
        $qb->where("p.type = :type")->setParameter(":type", $type);

        If ($date) {
            $qb->andWhere("(p.created = :created)")
                ->setParameter(":created", $date)
                ->setParameter(":created", $date);

        }

        return $qb->getQuery()->getSingleScalarResult();
    }
}
